export const FILTER_BY_CITY = 'filterByCity'
export const FILTER_BY_COMPANY= 'filterByCompany'
export const ORDER_BY_CITY = 'orderByCity'
export const ORDER_BY_NAME = 'orderByName'
export const ORDER_BY_COMPANY = 'orderByCompany'